---
  - hosts: localhost
    gather_facts: no
    module_defaults: 
      group/aws:
        region: "us-west-1"
        tags:
          Name: "Module5"
        state: present

    tasks:
      - name: Create VPC
        ec2_vpc_net:
          name: Module5
          cidr_block: 10.0.0.0/16
        register: vpc
      - name: Create public1 subnet
        ec2_vpc_subnet:
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.0.1.0/24
          az: "us-west-1a"
        register: public1_subnet
      - name: Create public2 subnet
        ec2_vpc_subnet:
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.0.2.0/24
          az: "us-west-1c"
        register: public2_subnet
      - name: Create private1 subnet
        ec2_vpc_subnet:
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.0.3.0/24
          az: "us-west-1a"
        register: private1_subnet
      - name: Create private2 subnet
        ec2_vpc_subnet:
          vpc_id: "{{ vpc.vpc.id }}"
          cidr: 10.0.4.0/24
          az: "us-west-1c" 
        register: private2_subnet
      - name: Create internet gateway
        ec2_vpc_igw:
          vpc_id: "{{ vpc.vpc.id }}"
        register: igw
      - name: Create public route table
        ec2_vpc_route_table:
          vpc_id: "{{ vpc.vpc.id }}"
          subnets: 
            - "{{ public1_subnet.subnet.id}}"
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ igw.gateway_id }}"
